// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/batch-05/adithya-kurniawan/final-project/house-booking-be/entity"
	mock "github.com/stretchr/testify/mock"
)

// ReservationUsecase is an autogenerated mock type for the ReservationUsecase type
type ReservationUsecase struct {
	mock.Mock
}

// AddReservation provides a mock function with given fields: _a0
func (_m *ReservationUsecase) AddReservation(_a0 *entity.Reservation) (*entity.Reservation, error) {
	ret := _m.Called(_a0)

	var r0 *entity.Reservation
	if rf, ok := ret.Get(0).(func(*entity.Reservation) *entity.Reservation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reservation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Reservation) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReservationUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewReservationUsecase creates a new instance of ReservationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReservationUsecase(t mockConstructorTestingTNewReservationUsecase) *ReservationUsecase {
	mock := &ReservationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
