// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/batch-05/adithya-kurniawan/final-project/house-booking-be/entity"
	mock "github.com/stretchr/testify/mock"
)

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: _a0
func (_m *AdminRepository) SignIn(_a0 *entity.Admin) (*entity.Admin, error) {
	ret := _m.Called(_a0)

	var r0 *entity.Admin
	if rf, ok := ret.Get(0).(func(*entity.Admin) *entity.Admin); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Admin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Admin) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignUp provides a mock function with given fields: _a0
func (_m *AdminRepository) SignUp(_a0 *entity.Admin) (*entity.Admin, error) {
	ret := _m.Called(_a0)

	var r0 *entity.Admin
	if rf, ok := ret.Get(0).(func(*entity.Admin) *entity.Admin); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Admin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Admin) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAdminRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminRepository(t mockConstructorTestingTNewAdminRepository) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
